- name: Install xxx
  hosts: server
  user: root
  roles:
    - yum-update
    - logwatch
    - user
  vars_prompt:
    - name: "user_password"
      prompt: "Enter password"
      private: yes
      confirm: yes
